name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: 'No user-facing changes.'

categories:
  - title: 'Features'
    labels: ['feat', 'feature']
  - title: 'Fixes'
    labels: ['fix', 'bugfix', 'bug']
  - title: 'Documentation'
    labels: ['docs']
  - title: 'Chores'
    labels: ['chore', 'refactor', 'ci']

version-resolver:
  major:
    labels: ['semver:major', 'breaking-change']
  minor:
    labels: ['semver:minor', 'feat', 'feature']
  patch:
    labels: ['semver:patch', 'fix', 'bugfix', 'bug', 'chore']
  default: patch

template: |
  ## Changes
  $CHANGES

  ## Contributors
  $CONTRIBUTORS

