---
extends: null
MD003: { style: "atx" }
MD004: { style: "asterisk" }
MD007: { indent: 2 }
MD009: { strict: true }
MD012: { maximum: 1 }
MD013:
  line_length: 120
  heading_line_length: 120
  code_block_line_length: 0
  tables: false
  heading_line_breaks: false
MD024:
  allow_different_nesting: true
MD026: { punctuation: "!?." }
MD029: { style: one }
MD033: { allowed_elements: ["div", "span"] }
MD041: { level: 1 }
