# Lidarr.Plugin.Common - Link Check Workflow Template
# Copy this to your plugin's .github/workflows/link-check.yml
# Requires .lychee.toml in your repository root (see templates/)

name: Link Check

on:
  pull_request:
    paths:
      - '**/*.md'
      - '.lychee.toml'
      - '.github/workflows/link-check.yml'
  push:
    paths:
      - '**/*.md'
      - '.lychee.toml'
      - '.github/workflows/link-check.yml'

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --config .lychee.toml
            --no-progress
            --verbose
            README.md docs/**/*.md
          fail: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
