using System.Reflection;

// Versioning and common assembly attributes are generated by the SDK
// from the project file (Title, Company, Product, Description, etc.).
// Keep only custom metadata here.
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/RicherTunes/Lidarr.Plugin.Common.git")]
