using System.Reflection;

// Versioning is generated by the SDK via <Version> in the project file.
// Keep only assembly metadata that is not generated by the SDK.
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/RicherTunes/Lidarr.Plugin.Common.git")]
